### ISSUE TITLE
what happened for the problem listed below??

### ISSUE THREAD

**Issue by guandailu** [JiangYuLab/CNVcaller#5]
[E::hts_open_format] fail to open file 'SRR5149617_RGSM.bam'
samtools view: failed to open "SRR5149617_RGSM.bam" for reading: No such file or directory
Unexpected bam format...

**Comment by biozzq** [comment]
Hi @guandailu 
Sorry for the later reply. Try passing the BAM files with the absolute path.

**Comment by JiangYuLab** [comment]
I am closing the issue, but feel free to reopen if needed.
