### ISSUE TITLE
Does the input BAM file need to remove PCR duplicate reads?

### ISSUE THREAD

**Issue by YiBenqiu** [JiangYuLab/CNVcaller#9]
Hi,  teacher
Do we need to remove duplication reads from the input BAM file before call CNV?

**Comment by biozzq** [comment]
Yes, you should mask the PCR duplication before calling.

**Comment by YiBenqiu** [comment]
Thank you, teacher!
But when I use "ndividual.Process.sh"  shell file , I encountered a new problem. 
my command is:
**bash ~/CNVcaller/Individual.Process.sh -b THH001.bam -h THH001 -d Sscrofa11.1_800_link -s X > $path/CNVcaller/log/THH001_absolute.log 2>&1**
and the log file:
**CNVcaller install directory /public/home/qiuyb/CNVcaller
refdb /public/home/qiuyb/CNV/CNVcaller/referenceDB.800
header THH001
duplicate file Sscrofa11.1_800_link
bam /public/home/qiuyb/CNV/RD_method/THH001.RD.bam
sex X
windowsize 800
stats read depth per window start!
Mon Nov  2 20:01:19 2020
Parsing sample THH001 ...
/public/home/qiuyb/CNV/RD_method/THH001.RD.bam file loading done!Mon Nov  2 20:22:58 2020
completed bam parsing!
raw reads count finished!
raw reads count file loading finished!
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, <LINK> line 1.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, <LINK> line 2.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, <LINK> line 3.**

Is this caused by the link file? Do I need to generate a link file by myself?

**Comment by YiBenqiu** [comment]
Thank you, teacher!
But when I use "**Individual.Process.sh**" shell file , I encountered a new problem.
my command is:
**bash ~/CNVcaller/Individual.Process.sh -b THH001.bam -h THH001 -d Sscrofa11.1_800_link -s X > $path/CNVcaller/log/THH001_absolute.log 2>&1**
and the log file:
**CNVcaller install directory /public/home/qiuyb/CNVcaller
refdb /public/home/qiuyb/CNV/CNVcaller/referenceDB.800
header THH001
duplicate file Sscrofa11.1_800_link
bam /public/home/qiuyb/CNV/RD_method/THH001.RD.bam
sex X
windowsize 800
stats read depth per window start!
Mon Nov 2 20:01:19 2020
Parsing sample THH001 ...
/public/home/qiuyb/CNV/RD_method/THH001.RD.bam file loading done!Mon Nov 2 20:22:58 2020
completed bam parsing!
raw reads count finished!
raw reads count file loading finished!
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 1.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 2.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 3.
.........
.........
.........**

Is this caused by the link file? Do I need to generate a link file by myself?

**Comment by YiBenqiu** [comment]
Thank you, teacher!
But when I use "**Individual.Process.sh**" shell file , I encountered a new problem.
my command is:
**bash ~/CNVcaller/Individual.Process.sh -b THH001.RD.bam -h THH001 -d Sscrofa11.1_800_link -s X > $path/CNVcaller/log/THH001_absolute.log 2>&1**
and the log file:
**CNVcaller install directory /public/home/qiuyb/CNVcaller
refdb /public/home/qiuyb/CNV/CNVcaller/referenceDB.800
header THH001
duplicate file Sscrofa11.1_800_link
bam /public/home/qiuyb/CNV/RD_method/THH001.RD.bam
sex X
windowsize 800
stats read depth per window start!
Mon Nov 2 20:01:19 2020
Parsing sample THH001 ...
/public/home/qiuyb/CNV/RD_method/THH001.RD.bam file loading done!Mon Nov 2 20:22:58 2020
completed bam parsing!
raw reads count finished!
raw reads count file loading finished!
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 1.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 2.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 3.
.........
.........
.........**

Is this caused by the link file? Do I need to generate a link file by myself?

**Comment by YiBenqiu** [comment]
Thank you, teacher!
But when I use "**Individual.Process.sh**" shell file , I encountered a new problem.
my command is:
**bash ~/CNVcaller/Individual.Process.sh -b THH001.RD.bam -h THH001 -d Sscrofa11.1_800_link -s X > $path/CNVcaller/log/THH001_absolute.log 2>&1**
and the log file:
**CNVcaller install directory /public/home/qiuyb/CNVcaller
refdb /public/home/qiuyb/CNV/CNVcaller/referenceDB.800
header THH001
duplicate file Sscrofa11.1_800_link
bam /public/home/qiuyb/CNV/RD_method/THH001.RD.bam
sex X
windowsize 800
stats read depth per window start!
Mon Nov 2 20:01:19 2020
Parsing sample THH001 ...
/public/home/qiuyb/CNV/RD_method/THH001.RD.bam file loading done!Mon Nov 2 20:22:58 2020
completed bam parsing!
raw reads count finished!
raw reads count file loading finished!
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 1.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 2.
Use of uninitialized value $pos in hash element at /public/home/qiuyb/CNVcaller/bin/1.2.CNVcorrect.pl line 23, line 3.
.........
.........
.........
**duplicated window record file loading finished!
corrected window number: 0
absolute reads counts correction finished!
absolute correct finished!**
.........
.........
.........**


Is this caused by the link file? Do I need to generate a link file by myself?

**Comment by YiBenqiu** [comment]
Hello, teacher. **I’ve solved this problem by creating my own link file**. The pig link file downloaded from the AOD site appears to be different from the demo link (name: dupfile) you provided.
the Sscrofa11.1_800_link downloaded from AOD website:
**CM000812.5-100026801	CM000812.5-100026401	KQ004242.1_2642000_2644000-1601	KQ004242.1_2642000_2644000-1201	CM000812.5-100026801
CM000812.5-100062001	LUXW01012492.1_644000_645615-401	CM000812.5-100061601	LUXW01012492.1_644000_645615-1	CM000812.5-100062001
CM000812.5-100062401	LUXW01012492.1_644000_645615-801	LUXW01012492.1_644000_645615-401	CM000812.5-100062401	CM000812.5-100062001**
.....
and demo link file:
**29:10068501	29:10068501	29:37307501	29:30795001
29:10069001	29:10069001	29:6289001	29:3501501	29:22485501	29:9795001	29:39989001	29:5863001	29:37307001**
......
......
But when I created the mergeCNVR file using the CNV.Discovery.sh , a new error occurred......
the log file:
**nohup: ignoring input
CNVcaller install directory /public/home/qiuyb/CNVcaller
referenceDB /public/home/qiuyb/CNV/CNVcaller/referenceDB.800
normalizedFileList list
excludedFileList exclude_list
windowsize 800
frequency 0.1
homozygous 3
pearsonCorrelation 0.5
primaryCNVR primaryCNVR
mergedCNVR mergeCNVR
2.16078947368421
/public/home/qiuyb/CNV/CNVcaller/RD_normalized/DHB00011_mean_70.38_SD_11.40_sex_1	0.35
/public/home/qiuyb/CNV/CNVcaller/RD_normalized/DHB00020_mean_97.02_SD_13.72_sex_1	0.35
/public/home/qiuyb/CNV/CNVcaller/RD_normalized/DHB0004_mean_102.06_SD_14.12_sex_1	0.35
sample number: 3
effective sample: 3
pearson correlation: 0.5
define effective window finished!
refine effective window finished!
primary CNVR define finished!
length() used on @tmp_start_array (did you mean "scalar(@tmp_start_array)"?) at /public/home/qiuyb/CNVcaller/bin/2.2.CNVRRedundancy.pl line 48.
length() used on @tmp (did you mean "scalar(@tmp)"?) at /public/home/qiuyb/CNVcaller/bin/2.2.CNVRRedundancy.pl line 48.
merge CNVR finished!**

It seems somthing wrong in 2.2.CNVRRedundancy.pl .......I was so confused. Could this be an error caused by the Perl version？

**Comment by YiBenqiu** [comment]
I tried changing the Perl version to 5.10.1 using perlbrew. And then it’s back to normal !!!
Thank you teacher.
